/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FormButton: typeof import('./src/components/form/FormButton.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PullRequestStatusIcon: typeof import('./src/components/PullRequestStatusIcon.vue')['default']
    PullRequestTable: typeof import('./src/components/PullRequestTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
